-- ============================================================
-- DEV SEED DATA — 20 realistic fake analyzed_events
-- ============================================================

-- Ensure raw feeds exist to prevent FK issues if referencing raw_feed
-- Since raw_feed has guid and pub_date as PK, let's insert there first:
INSERT INTO raw_feed (guid, title, link, description, pub_date, category, ticker, processed)
VALUES
('guid-1', 'Infosys (INFY) Q4 Revenue Beats Estimates by 4.2%', 'https://www.nseindia.com/filings/1', 'Infosys announced its Q4 results with strong revenue growth in cloud services.', '2026-06-15 10:00:00+00', 'financial_results', 'INFY', true),
('guid-2', 'Tata Consultancy Services (TCS) Wins $500M Cloud Migration Deal', 'https://www.nseindia.com/filings/2', 'TCS has partnered with a major European bank for digital transformation.', '2026-06-15 11:00:00+00', 'announcements', 'TCS', true),
('guid-3', 'Reliance Industries (RELIANCE) Announces Board Meeting for Dividend', 'https://www.nseindia.com/filings/3', 'A board meeting will be held next week to approve final dividend.', '2026-06-15 12:00:00+00', 'board_meeting', 'RELIANCE', true),
('guid-4', 'HDFC Bank (HDFCBANK) Net Profit drops 12% on high NPAs', 'https://www.nseindia.com/filings/4', 'HDFC Bank reports higher provisioning for bad loans this quarter.', '2026-06-16 09:30:00+00', 'financial_results', 'HDFCBANK', true),
('guid-5', 'Tata Motors (TATAMOTORS) Insider Acquisition of 50,000 Equity Shares', 'https://www.nseindia.com/filings/5', 'Promoters acquire additional stake via open market transactions.', '2026-06-16 14:00:00+00', 'insider_trading', 'TATAMOTORS', true),
('guid-6', 'Wipro (WIPRO) Announces Share Buyback at Rs 620 per share', 'https://www.nseindia.com/filings/6', 'Board approves buyback of up to 40 million equity shares.', '2026-06-17 10:15:00+00', 'buyback', 'WIPRO', true),
('guid-7', 'Larsen & Toubro (LT) Secures Mega Infrastructure Contract in India', 'https://www.nseindia.com/filings/7', 'L&T Construction wins order worth over Rs 5000 Crore.', '2026-06-17 11:45:00+00', 'announcements', 'LT', true),
('guid-8', 'Axis Bank (AXISBANK) Receives 1200 Investor Complaints in May', 'https://www.nseindia.com/filings/8', 'Monthly reporting on complaints resolution shows rise in pending cases.', '2026-06-18 15:00:00+00', 'investor_complaints', 'AXISBANK', true),
('guid-9', 'ITC Limited (ITC) Shareholding Pattern Shows Increased FII Inflow', 'https://www.nseindia.com/filings/9', 'Foreign institutional investors raise stake in ITC to 14.8%.', '2026-06-18 16:30:00+00', 'shareholding_pattern', 'ITC', true),
('guid-10', 'State Bank of India (SBIN) Annual Report highlights digital initiatives', 'https://www.nseindia.com/filings/10', 'SBI details YONO expansion and robust balance sheet growth.', '2026-06-19 11:00:00+00', 'annual_report', 'SBIN', true),
('guid-11', 'Bharti Airtel (BHARTIALRT) Launches New 5G AI-Native Data Centers', 'https://www.nseindia.com/filings/11', 'Airtel expands enterprise footprint with eco-friendly edge centers.', '2026-06-19 13:15:00+00', 'announcements', 'BHARTIALRT', true),
('guid-12', 'Maruti Suzuki (MARUTI) reports decline in monthly production volume', 'https://www.nseindia.com/filings/12', 'Production levels decreased by 3% due to supply chain disruptions.', '2026-06-20 09:20:00+00', 'announcements', 'MARUTI', true),
('guid-13', 'HCL Technologies (HCLTECH) Board Meeting scheduled for October 12', 'https://www.nseindia.com/filings/13', 'The board will declare third quarter interim dividend during the meet.', '2026-06-20 12:40:00+00', 'board_meeting', 'HCLTECH', true),
('guid-14', 'Asian Paints (ASIANPAINT) Corporate Action details: 1:1 Bonus Issue', 'https://www.nseindia.com/filings/14', 'ASIANPAINT updates record date for the upcoming bonus issue.', '2026-06-21 10:00:00+00', 'corporate_action', 'ASIANPAINT', true),
('guid-15', 'Sun Pharmaceutical (SUNPHARMA) Promoter sells 1 million shares', 'https://www.nseindia.com/filings/15', 'Promoter entity sells stake worth Rs 140 Crore in open market.', '2026-06-21 15:30:00+00', 'insider_trading', 'SUNPHARMA', true),
('guid-16', 'Mahindra & Mahindra (M&M) Launches Advanced EV Platform INGLO', 'https://www.nseindia.com/filings/16', 'M&M accelerates EV transition with global modular architecture.', '2026-06-22 09:15:00+00', 'announcements', 'M&M', true),
('guid-17', 'NTPC Limited (NTPC) Q1 Power Generation Up by 8%', 'https://www.nseindia.com/filings/17', 'NTPC records highest quarterly generation across coal and hydro plants.', '2026-06-22 10:30:00+00', 'financial_results', 'NTPC', true),
('guid-18', 'Titan Company (TITAN) Investor Complaints Resolved in 24 Hours', 'https://www.nseindia.com/filings/18', 'Titan maintains 100% resolution rate for retail investor grievances.', '2026-06-22 14:15:00+00', 'investor_complaints', 'TITAN', true),
('guid-19', 'UltraTech Cement (ULTRACEMCO) Declining Promoter Stake in Shareholding', 'https://www.nseindia.com/filings/19', 'Promoters reduce holding by 0.5% in the quarterly reporting cycle.', '2026-06-22 16:00:00+00', 'shareholding_pattern', 'ULTRACEMCO', true),
('guid-20', 'Kotak Mahindra Bank (KOTAKBANK) Board approves CEO Succession Plan', 'https://www.nseindia.com/filings/20', 'Kotak Bank submits application to RBI for approval of incoming CEO.', '2026-06-22 17:00:00+00', 'board_meeting', 'KOTAKBANK', true)
ON CONFLICT (guid, pub_date) DO NOTHING;

-- Seed Analyzed Events
-- Automatically triggers update_company_agg() trigger
INSERT INTO analyzed_events (raw_feed_id, ticker, company_name, category, headline, sentiment, score, rationale, keywords, pub_date)
VALUES
((SELECT id FROM raw_feed WHERE guid = 'guid-1'), 'INFY', 'Infosys Limited', 'financial_results', 'Infosys (INFY) Q4 Revenue Beats Estimates by 4.2%', 'positive', 85, 'Revenue beat analyst estimates with cloud services showing strength.', '{"cloud services", "revenue", "estimates"}', '2026-06-15 10:00:00+00'),
((SELECT id FROM raw_feed WHERE guid = 'guid-2'), 'TCS', 'Tata Consultancy Services', 'announcements', 'Tata Consultancy Services (TCS) Wins $500M Cloud Migration Deal', 'positive', 92, 'TCS has partnered with a major European bank for digital transformation.', '{"cloud migration", "partnership"}', '2026-06-15 11:00:00+00'),
((SELECT id FROM raw_feed WHERE guid = 'guid-3'), 'RELIANCE', 'Reliance Industries Limited', 'board_meeting', 'Reliance Industries (RELIANCE) Announces Board Meeting for Dividend', 'neutral', 50, 'A board meeting will be held next week to approve final dividend.', '{"board meeting", "dividend"}', '2026-06-15 12:00:00+00'),
((SELECT id FROM raw_feed WHERE guid = 'guid-4'), 'HDFCBANK', 'HDFC Bank Limited', 'financial_results', 'HDFC Bank (HDFCBANK) Net Profit drops 12% on high NPAs', 'negative', 15, 'Results missed estimates with pressure on provisioning.', '{"net profit", "NPA", "bad loans"}', '2026-06-16 09:30:00+00'),
((SELECT id FROM raw_feed WHERE guid = 'guid-5'), 'TATAMOTORS', 'Tata Motors Limited', 'insider_trading', 'Tata Motors (TATAMOTORS) Insider Acquisition of 50,000 Equity Shares', 'positive', 78, 'Insider buying signals management confidence in Tata Motors.', '{"insider buying", "equity shares", "promoters"}', '2026-06-16 14:00:00+00'),
((SELECT id FROM raw_feed WHERE guid = 'guid-6'), 'WIPRO', 'Wipro Limited', 'buyback', 'Wipro (WIPRO) Announces Share Buyback at Rs 620 per share', 'positive', 82, 'Buyback signals management conviction in Wipro undervaluing.', '{"share buyback", "equity"}', '2026-06-17 10:15:00+00'),
((SELECT id FROM raw_feed WHERE guid = 'guid-7'), 'LT', 'Larsen & Toubro Limited', 'announcements', 'Larsen & Toubro (LT) Secures Mega Infrastructure Contract in India', 'positive', 89, 'L&T Construction wins order worth over Rs 5000 Crore.', '{"infrastructure", "order win"}', '2026-06-17 11:45:00+00'),
((SELECT id FROM raw_feed WHERE guid = 'guid-8'), 'AXISBANK', 'Axis Bank Limited', 'investor_complaints', 'Axis Bank (AXISBANK) Receives 1200 Investor Complaints in May', 'negative', 28, 'Monthly reporting on complaints resolution shows rise in pending cases.', '{"complaints", "pending"}', '2026-06-18 15:00:00+00'),
((SELECT id FROM raw_feed WHERE guid = 'guid-9'), 'ITC', 'ITC Limited', 'shareholding_pattern', 'ITC Limited (ITC) Shareholding Pattern Shows Increased FII Inflow', 'positive', 76, 'FII/DII inflow indicates institutional confidence in ITC.', '{"FII inflow", "institutional"}', '2026-06-18 16:30:00+00'),
((SELECT id FROM raw_feed WHERE guid = 'guid-10'), 'SBIN', 'State Bank of India', 'annual_report', 'State Bank of India (SBIN) Annual Report highlights digital initiatives', 'neutral', 53, 'SBI details YONO expansion and robust balance sheet growth.', '{"annual report", "digital"}', '2026-06-19 11:00:00+00'),
((SELECT id FROM raw_feed WHERE guid = 'guid-11'), 'BHARTIALRT', 'Bharti Airtel Limited', 'announcements', 'Bharti Airtel (BHARTIALRT) Launches New 5G AI-Native Data Centers', 'positive', 80, 'Airtel expands enterprise footprint with eco-friendly edge centers.', '{"5G", "AI-native data centers"}', '2026-06-19 13:15:00+00'),
((SELECT id FROM raw_feed WHERE guid = 'guid-12'), 'MARUTI', 'Maruti Suzuki India Limited', 'announcements', 'Maruti Suzuki (MARUTI) reports decline in monthly production volume', 'negative', 35, 'Production levels decreased by 3% due to supply chain disruptions.', '{"monthly production", "supply chain"}', '2026-06-20 09:20:00+00'),
((SELECT id FROM raw_feed WHERE guid = 'guid-13'), 'HCLTECH', 'HCL Technologies Limited', 'board_meeting', 'HCL Technologies (HCLTECH) Board Meeting scheduled for October 12', 'neutral', 50, 'The board will declare third quarter interim dividend during the meet.', '{"board meeting", "dividend"}', '2026-06-20 12:40:00+00'),
((SELECT id FROM raw_feed WHERE guid = 'guid-14'), 'ASIANPAINT', 'Asian Paints Limited', 'corporate_action', 'Asian Paints (ASIANPAINT) Corporate Action details: 1:1 Bonus Issue', 'positive', 72, 'Corporate action indicates shareholder value creation at Asian Paints.', '{"bonus issue", "record date"}', '2026-06-21 10:00:00+00'),
((SELECT id FROM raw_feed WHERE guid = 'guid-15'), 'SUNPHARMA', 'Sun Pharmaceutical Industries', 'insider_trading', 'Sun Pharmaceutical (SUNPHARMA) Promoter sells 1 million shares', 'negative', 30, 'Insider selling raises caution flags for Sun Pharmaceutical.', '{"insider selling", "promoters"}', '2026-06-21 15:30:00+00'),
((SELECT id FROM raw_feed WHERE guid = 'guid-16'), 'M&M', 'Mahindra & Mahindra Limited', 'announcements', 'Mahindra & Mahindra (M&M) Launches Advanced EV Platform INGLO', 'positive', 84, 'M&M accelerates EV transition with global modular architecture.', '{"EV platform", "modular"}', '2026-06-22 09:15:00+00'),
((SELECT id FROM raw_feed WHERE guid = 'guid-17'), 'NTPC', 'NTPC Limited', 'financial_results', 'NTPC Limited (NTPC) Q1 Power Generation Up by 8%', 'positive', 75, 'NTPC records highest quarterly generation across coal and hydro plants.', '{"power generation", "coal"}', '2026-06-22 10:30:00+00'),
((SELECT id FROM raw_feed WHERE guid = 'guid-18'), 'TITAN', 'Titan Company Limited', 'investor_complaints', 'Titan Company (TITAN) Investor Complaints Resolved in 24 Hours', 'positive', 65, 'Titan maintains 100% resolution rate for retail investor grievances.', '{"investor complaints", "resolution"}', '2026-06-22 14:15:00+00'),
((SELECT id FROM raw_feed WHERE guid = 'guid-19'), 'ULTRACEMCO', 'UltraTech Cement Limited', 'shareholding_pattern', 'UltraTech Cement (ULTRACEMCO) Declining Promoter Stake in Shareholding', 'negative', 40, 'Declining promoter stake reflects potential change in allocation.', '{"promoter stake", "shareholding"}', '2026-06-22 16:00:00+00'),
((SELECT id FROM raw_feed WHERE guid = 'guid-20'), 'KOTAKBANK', 'Kotak Mahindra Bank Limited', 'board_meeting', 'Kotak Mahindra Bank (KOTAKBANK) Board approves CEO Succession Plan', 'neutral', 52, 'Kotak Bank submits application to RBI for approval of incoming CEO.', '{"CEO succession", "board approval"}', '2026-06-22 17:00:00+00');
